package ifneeded dgtools::dgtutils 0.1 [list source [file join $dir dgtutils-0.1.tm]]
package ifneeded dgtools::argvparse 0.2 [list source [file join $dir argvparse-0.2.tm]]
package ifneeded dgtools::shistory 0.2 [list source [file join $dir shistory-0.2.tm]]
package ifneeded dgtools::repo 0.1 [list source [file join $dir repo-0.1.tm]]
package ifneeded dgtools::recover 0.1 [list source [file join $dir recover-0.1.tm]]
